services:
    postgres:
        container_name: teebay-postgres
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: teebay
            POSTGRES_PASSWORD: postgres

volumes:
    postgres_data:
